[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "LS_COLORS manager with multiple themes"
homepage = "https://github.com/sharkdp/dircolors-hd"
license = "MIT/Apache-2.0"
name = "dircolors-hd"
readme = "README.md"
repository = "https://github.com/sharkdp/dircolors-hd"
version = "0.1.0"

[dependencies]
yaml-rust = "0.4"
lazy_static = "1.2.0"

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]
