core:
  regular_file: [$fi]
  directory: [$di]

  executable_file: [$ex]

  symlink: [$ln]
  broken_symlink: [$or, $mi]

  fifo: [$pi]
  socket: [$so]

  normal_text: [$no]

text:
  special:
    - CONTRIBUTORS
    - CONTRIBUTORS.md
    - CONTRIBUTORS.txt
    - README
    - README.md
    - README.txt

  important:
    - TODO
    - TODO.md
    - TODO.txt

  licenses:
    - LICENSE
    - LICENSE-MIT
    - LICENSE-APACHE
    - COPYING

  configuration:
    generic:
      - .conf
      - .cfg

  other:
    - .txt

markup:
  web:
    - .css
    - .htm
    - .html
    - .shtml
    - .xhtml
    - .less

  other:
    - .json
    - .md
    - .markdown
    - .mdown
    - .tex
    - .toml
    - .tml
    - .xml
    - .yaml
    - .yml
    - .xmp
    - .csv

programming:
  source:
    actionscript: [.as]
    applescript: [.applescript]
    asp: [.asa]
    awk: [.awk]
    batch: [.bat, .cmd]
    bibtex: [.bib]
    shell: [.sh, .bash, .zsh, .fish]
    c: [.c, .h]
    csharp: [.cs, .csx]
    cxx: [.cpp, .cc, .cp, .cxx, .c++, .C, .h, .hh, .hpp, .hxx, .h++, .inl, .ipp]
    cabal: [.cabal]
    clojure: [.clj]
    crystal: [.cr]
    d: [.d, .di]
    dart: [.dart]
    diff: [.diff, .patch]
    dockerfile: [Dockerfile, dockerfile]
    elixir: [.ex, .exs]
    elm: [.elm]
    erlang: [.erl]
    fsharp: [.fs, .fsi, .fsx]
    go: [.go]
    graphviz: [.dot, .DOT, .gv]
    groovy: [.groovy, .gvy, .gradle]
    haskell: [.hs]
    java: [.java, .bsh]
    javascript: [.js, .htc]
    julia: [.jl]
    kotlin: [.kt, .kts]
    latex: [.tex, .ltx]
    less: [.less]
    lisp: [.lisp, .el]
    literate haskell: [.lhs]
    lua: [.lua]
    matlab: [.matlab]
    nix: [.nix]
    ocaml: [.ml, .mli]
    pascal: [.pas, .p, .dpr]
    perl: [.pl, .pm, .pod, .t, .PL]
    php: [.php]
    powershell: [.ps1, .psm1, .psd1]
    puppet: [.pp, .epp]
    purescript: [.purs]
    python: [.py]
    r: [.R, .r]
    ruby: [.rb]
    rust: [.rs]
    scala: [.scala, .sbt]
    sql: [.sql]
    swift: [.swift]
    tcl: [.tcl]
    typescript: [.ts]
    typescriptreact: [.tsx]
    viml: [.vim]

  vcs:
    git:
      - .gitignore
      - .gitmodules
      - .gitattributes
      - .gitconfig
      - .gitconfig

    hg:
      - .hgrc
      - hgrc

    other:
      - .ignore
      - .fdignore
      - .rgignore

  build:
    cmake:
      - .cmake
      - CMakeLists.txt

    make:
      - Makefile
      - .make

    scons:
      - SConscript
      - SConstruct

  ci:
    - appveyor.yml
    - .travis.yml

media:
  image:
    - .jpg
    - .png
    - .jpeg
    - .svg
    - .bmp
    - .gif

  audio:
    - .wav
    - .flac
    - .mp3

  video:
    - .mkv
    - .mov
    - .mp4
    - .mpeg
    - .mpg
    - .wmv

office:
  document:
    - .doc
    - .docx
    - .pdf

  sheet:
    - .xls
    - .xlsx

  presentation:
    - .ppt
    - .pptx

archives:
  packages:
    - .apk
    - .deb
    - .rpm

  other:
    - .7z
    - .bz
    - .bz2
    - .gz
    - .iso
    - .jar
    - .rar
    - .tar
    - .tbz
    - .tbz2
    - .tgz
    - .z
    - .zip

executable:
  windows:
    - .bat
    - .cmd
    - .exe

unimportant:
  - "~"
  - .bak
  - .git  # only works for '.git' files (submodules)
  - .lock
  - .log
  - .o
  - .orig
  - .pyc
  - .scons_opt
  - .sconsign.dblite
  - CMakeCache.txt
  - package-lock.json
