core:
  regular_file: [$fi]
  directory: [$di]

  executable_file: [$ex]

  symlink: [$ln]
  broken_symlink: [$or, $mi]

  fifo: [$pi]
  socket: [$so]

  normal_text: [$no]

text:
  special:
    - CONTRIBUTORS
    - CONTRIBUTORS.md
    - CONTRIBUTORS.txt
    - INSTALL
    - INSTALL.md
    - INSTALL.md.txt
    - README
    - README.md
    - README.txt

  todo:
    - TODO
    - TODO.md
    - TODO.txt

  licenses:
    - COPYING
    - COPYRIGHT
    - LICENSE
    - LICENSE-APACHE
    - LICENSE-MIT

  configuration:
    generic:
      - .cfg
      - .conf
      - .config
      - .ini
      - .json
      - .tml
      - .toml
      - .yaml
      - .yml

    metadata:
      - .xmp

    bibtex:
      - .bib
      - .bst

    dockerfile:
      - Dockerfile

    nix:
      - .nix

    qt:
      - .ui

    desktop:
      - .desktop

    system:
      - passwd
      - shadow

  other:
    - .txt

markup:
  web:
    - .htm
    - .html
    - .shtml
    - .xhtml

  other:
    - .csv
    - .markdown
    - .md
    - .mdown
    - .rst
    - .xml

programming:
  source:
    actionscript: [.as]
    applescript: [.applescript]
    asp: [.asa]
    awk: [.awk]
    basic: [.vb]
    shell: [.sh, .bash, .zsh, .fish]
    csharp: [.cs, .csx]
    css: [css]
    cxx: [.c, .cpp, .cc, .cp, .cxx, .c++, .h, .hh, .hpp, .hxx, .h++, .inl, .ipp]
    cabal: [.cabal]
    clojure: [.clj]
    crystal: [.cr]
    d: [.d, .di]
    dart: [.dart]
    diff: [.diff, .patch]
    elixir: [.ex, .exs]
    elm: [.elm]
    erlang: [.erl]
    fsharp: [.fs, .fsi, .fsx]
    go: [.go]
    graphviz: [.dot, .gv]
    groovy: [.groovy, .gvy, .gradle]
    haskell: [.hs]
    java: [.java, .bsh]
    javascript: [.js, .htc]
    julia: [.jl]
    kotlin: [.kt, .kts]
    latex: [.tex, .ltx]
    less: [.less]
    lisp: [.lisp, .el]
    lua: [.lua]
    matlab: [.matlab, .m, .mn]
    mathematica: [.nb]
    ocaml: [.ml, .mli]
    pascal: [.pas, .p, .dpr]
    perl: [.pl, .pm, .pod, .t, .cgi]
    php: [.php]
    powershell: [.ps1, .psm1, .psd1]
    puppet: [.pp, .epp]
    purescript: [.purs]
    python: [.py]
    ipython: [.ipynb]
    r: [.r]
    ruby: [.rb]
    rust: [.rs]
    scala: [.scala, .sbt]
    sql: [.sql]
    swift: [.swift]
    tcl: [.tcl]
    typescript: [.ts, .tsx]
    viml: [.vim]

  tooling:
    vcs:
      git:
        - .gitignore
        - .gitmodules
        - .gitattributes
        - .gitconfig

      hg:
        - .hgrc
        - hgrc

      other:
        - CODEOWNERS
        - .ignore
        - .fdignore
        - .rgignore

    build:
      cmake:
        - .cmake
        - CMakeLists.txt
        - .cmake.in

      make:
        - Makefile
        - .make

      automake:
        - Makefile.am

      configure:
        - configure
        - configure.ac

      scons:
        - SConscript
        - SConstruct

      pip:
        - requirements.txt

    packaging:
      python:
        - MANIFEST.in
        - setup.py
      ruby:
        - .gemspec

    code-style:
      python:
        - .flake8

      cxx:
        - .clang-format

    editors:
      qt:
        - .pro
      kdevelop:
        - .kdevelop

    documentation:
      doxygen:
        - Doxyfile
        - .dox

    continuous-integration:
      - appveyor.yml
      - .travis.yml

media:
  image:
    - .jpg
    - .png
    - .jpeg
    - .svg
    - .bmp
    - .gif

  audio:
    - .wav
    - .flac
    - .mp3

  video:
    - .mkv
    - .mov
    - .mp4
    - .mpeg
    - .mpg
    - .wmv

office:
  document:
    - .doc
    - .docx
    - .pdf

  sheet:
    - .xls
    - .xlsx

  presentation:
    - .ppt
    - .pptx

archives:
  packages:
    - .apk
    - .deb
    - .rpm

  ros:
    - .bag

  other:
    - .7z
    - .bz
    - .bz2
    - .gz
    - .iso
    - .jar
    - .rar
    - .tar
    - .tbz
    - .tbz2
    - .tgz
    - .z
    - .zip

executable:
  windows:
    - .bat
    - .cmd
    - .exe

unimportant:
  build_artifacts:
    cxx:
      - .o
    cmake:
      - CMakeCache.txt
    rust:
      - .rlib
    python:
      - .pyc
    scons:
      - .scons_opt
      - .sconsign.dblite
    latex:
      - .aux
      - .bbl
      - .bcf
      - .blg
      - .fls
      - .out
      - .toc
      - .synctex.gz
      - .fdb_latexmk

  other:
    - "~"
    - .bak
    - .git  # only works for '.git' files (submodules)
    - .lock
    - .log
    - .orig
    - package-lock.json
